### ISSUE TITLE
Cannot open Second notebook: Solubility classification in Colab

### ISSUE THREAD

**Issue by marmatti** [Edinburgh-Chemistry-Teaching/ATCP_23_24#1]
Although I can open the first notebook, whenever I try to open the second one I get: 
**Notebook not found!** Error while loading the notebook. Ensure the file is accessible and try again. Ensure you have the correct authorization to visualise this notebook in GitHub and authorise Colab to use the API of Github.

Then there is the following link to the github page
https://github.com/Edinburgh-Chemistry-Teaching/ATCP_23_24/blob/main/Unit_03/02_Solubility_classification.ipynbi

If I follow it:
![image](https://github.com/Edinburgh-Chemistry-Teaching/ATCP_23_24/assets/61904349/54e23316-cfac-483b-aed8-2ea9486b7635)

**Comment by ppxasjsm** [comment]
Try now! There was a typo.
